return {
  -- Git symbols
  git = {
    Add = '',
    Branch = '',
    Change = '',
    Conflict = '',
    Delete = '',
    Ignored = '◌',
    Renamed = '➜',
    Sign = '▎',
    Staged = '✓',
    Unstaged = '✗',
    Untracked = '★',
  },

  -- Diagnostic symbols
  diagnostics = {
    Error = '',
    Hint = '󰌵',
    Info = '󰋼',
    Warn = '',
  },

  -- Symbol kinds
  kinds = {
    Array = ' ',
    Boolean = '󰨙 ',
    Class = ' ',
    Codeium = '󰘦 ',
    Color = ' ',
    Control = ' ',
    Collapsed = ' ',
    Constant = '󰏿 ',
    Constructor = ' ',
    Enum = ' ',
    EnumMember = ' ',
    Event = ' ',
    Field = ' ',
    File = ' ',
    Folder = ' ',
    Function = '󰊕 ',
    Interface = ' ',
    Key = ' ',
    Keyword = ' ',
    Method = '󰊕 ',
    Module = ' ',
    Namespace = '󰦮 ',
    Null = ' ',
    Number = '󰎠 ',
    Object = ' ',
    Operator = ' ',
    Package = ' ',
    Property = ' ',
    Reference = ' ',
    Snippet = ' ',
    String = ' ',
    Struct = '󰆼 ',
    Text = ' ',
    TypeParameter = ' ',
    Unit = ' ',
    Value = ' ',
    Variable = '󰀫 ',
  },

  -- DAP symbols
  dap = {
    Breakpoint = '',
    BreakpointCondition = '',
    BreakpointRejected = '',
    LogPoint = '󰛿',
    Stopped = '󰁕',
    Debugger = '',
  },
}
