return {
  {
    'nvim-treesitter/nvim-treesitter',
    build = ':TSUpdate',
    event = 'VeryLazy',
    init = function(plugin)
      require('lazy.core.loader').add_to_rtp(plugin)
      require('nvim-treesitter.query_predicates')
    end,
    cmd = {
      'TSBufDisable',
      'TSBufEnable',
      'TSBufToggle',
      'TSDisable',
      'TSEnable',
      'TSToggle',
      'TSInstall',
      'TSInstallInfo',
      'TSInstallSync',
      'TSModuleInfo',
      'TSUninstall',
      'TSUpdate',
      'TSUpdateSync',
    },
    opts = {
      ensure_installed = {
        'go',
        'gomod',
        'gosum',
        'rust',
        'bash',
        'javascript',
        'jsdoc',
        'typescript',
        'tsx',
        'lua',
        'markdown',
        'markdown_inline',
        'query',
        'vim',
        'vimdoc',
        'typst',
        'json',
        'jsonc',
        'yaml',
        'nix',
        'html',
        'css',
        'scss',
        'vue',
        'dockerfile',
        'gitcommit',
        'git_rebase',
        'gitignore',
        'gitattributes',
        'json5',
        'sql',
        'toml',
      },
      highlight = { enable = true },
      indent = { enable = true },
      incremental_selection = {
        enable = true,
        keymaps = {
          init_selection = '<C-space>',
          node_incremental = '<C-space>',
          scope_incremental = false,
          node_decremental = '<bs>',
        },
      },
    },
    config = function(_, opts) require('nvim-treesitter.configs').setup(opts) end,
  },

  {
    'windwp/nvim-ts-autotag',
    ft = { 'html', 'vue', 'jsx', 'tsx' },
    opts = {},
  },
}
